<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.24.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntegradorDominio\IntegradorDominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infraestrutura\Versionamento\" />
  </ItemGroup>

</Project>
